### ISSUE TITLE
generation of condensed Gabor filters

### ISSUE THREAD

**Issue by nelson0707** [chengyawlow/MFFC#1]
Hi, there are something wrong when generating new condensed gabor filters with new size (e.g. 9).
It is very different from the fig3a in the paper. Could you give some tips of generating new condensed gabor filters? Thanks in advance : )

**Comment by chengyawlow** [comment]
The MATLAB codes for computing condensed Gabor filters are as follows:

function GaborFilt_COND_MAIN( GaborFilt_ORIENTATION, GaborFilt_SCALE, GaborFilt_HEIGHT, GaborFilt_WIDTH )
    
    %% Initialize GaborFilt_ORIENTATION, GaborFilt_SCALE, GaborFilt_HEIGHT, GaborFilt_WIDTH
    if nargin == 0
        GaborFilt_ORIENTATION = 8;
        GaborFilt_SCALE = 5;
        GaborFilt_HEIGHT = 7;
        GaborFilt_WIDTH = 7;
    end
    assert( nargin == 0 || nargin == 4 );

    %% Formulate GaborFilt_REAL & GaborFilt_IMG 
    GaborFilt_REAL = cell(  1, GaborFilt_ORIENTATION );
    GaborFilt_IMG = cell(  1, GaborFilt_ORIENTATION );

    for SCALE_ID = 0 : GaborFilt_SCALE - 1
        
        for ORIENTATION_ID = 0 : GaborFilt_ORIENTATION - 1   
            
			[ GaborFilt_REAL_TEMP, GaborFilt_IMG_TEMP ] = formulateGaborFilt( GaborFilt_HEIGHT, GaborFilt_WIDTH, GaborFilt_ORIENTATION, ORIENTATION_ID, SCALE_ID );
            
			GaborFilt_REAL{ ORIENTATION_ID + 1 } = cat( 3, GaborFilt_REAL{ ORIENTATION_ID + 1 }, GaborFilt_REAL_TEMP );
			GaborFilt_IMG{ ORIENTATION_ID + 1 } = cat( 3, GaborFilt_IMG{ ORIENTATION_ID + 1 }, GaborFilt_IMG_TEMP );
            
			clear GaborFilt_REAL_TEMP GaborFilt_IMG_TEMP;
			pause( 0.0001 );
           
        end
        
    end
    
    %% Construct GaborFilt_COND_REAL, GaborFilt_COND_IMG
    GaborFilt_COND_REAL = zeros( GaborFilt_HEIGHT * GaborFilt_WIDTH, GaborFilt_ORIENTATION );
    GaborFilt_COND_IMG = zeros( GaborFilt_HEIGHT * GaborFilt_WIDTH, GaborFilt_ORIENTATION );
    
    for ORIENTATION_ID = 1 : GaborFilt_ORIENTATION
        
        GaborFilt_COND_REAL_TEMP = GaborFilt_REAL{ ORIENTATION_ID };            
        GaborFilt_COND_REAL_TEMP = mean( GaborFilt_COND_REAL_TEMP, 3 );
        % Optional mean-removal
		GaborFilt_COND_REAL( :, ORIENTATION_ID ) = GaborFilt_COND_REAL_TEMP(:) - mean( GaborFilt_COND_REAL_TEMP(:) );

        GaborFilt_COND_IMG_TEMP = GaborFilt_IMG{ ORIENTATION_ID };       
        GaborFilt_COND_IMG_TEMP = mean( GaborFilt_COND_IMG_TEMP, 3 );
        % Optional mean-removal
		GaborFilt_COND_IMG( :, ORIENTATION_ID ) = GaborFilt_COND_IMG_TEMP(:) - mean( GaborFilt_COND_IMG_TEMP(:) );
                               
    end 
	
    %% Define V & W, accordingly
    %  Optional L2-Norm
	V{ 1 } = normc( GaborFilt_COND_REAL );
	W{ 1 } = normc( GaborFilt_COND_IMG );
    
end

function [ GaborFilt_REAL, GaborFilt_IMG ] = formulateGaborFilt( GaborFilt_HEIGHT, GaborFilt_WIDTH, GaborFilt_ORIENTATION, U, V)

	%% Parameter Initialization
    HarfH = fix( GaborFilt_HEIGHT / 2 );
	HarfW = fix( GaborFilt_WIDTH / 2 );
	
	kmax = pi / 2;
    f = sqrt( 2 );
    sigma = 2 * pi;

	Qu      = pi * U / GaborFilt_ORIENTATION;
	sqsigma = sigma * sigma;
	Kv      = kmax /( f ^ V );
	postmean = exp( -sqsigma / 2 );

    %% Compute GaborFilt_REAL, GaborFilt_IMG
    for j = -HarfH : HarfH
		
        for i =  -HarfW : HarfW
			
			tmp1 = exp( -( Kv * Kv * ( j * j + i * i ) / ( 2 * sqsigma ) ) );
			tmp2 = cos( Kv * cos( Qu ) * i + Kv * sin( Qu ) * j ) - postmean;
			tmp3 = sin( Kv * cos( Qu ) * i + Kv * sin( Qu ) * j ); % - postmean;
		   
			GaborFilt_REAL( j + HarfH + 1, i + HarfW + 1 ) = Kv * Kv * tmp1 * tmp2/ sqsigma;
			GaborFilt_IMG( j + HarfH + 1, i + HarfW + 1) = Kv * Kv * tmp1 * tmp3 / sqsigma;
			
        end
        
    end

end

**Comment by nelson0707** [comment]
Thank you! 
and one more question, an error occurred while setting the overlapping ratio to 0.5. It said that MFFC.SpatialPyramid_LEVEL is undefined. How to set the value of the SpatialPyramid_LEVEL?

**Comment by chengyawlow** [comment]
Yup the uploaded codes do not support overlapping feature encoding.
For overlapping ratio ~= 0, please refer to the original PCANet implementation.
http://mx.nthu.edu.tw/~tsunghan/Source%20codes.html
